"""Adapter contracts and per-module CLI wrappers.

Import `adapters.base` for the shared types. Module stubs under this package
are intentionally not wired to live LLM / data runs.
"""

from .base import (
    ALL_SUITE_IDS,
    DEFAULT_KERNEL_SUITE_ID,
    OPTIONAL_SUITE_IDS,
    REQUIRED_SUITE_IDS,
    SCHEMA_VERSION,
    BenchTier,
    AcceptanceReport,
    Admission,
    AdmissionDecision,
    AgentAdapter,
    AgentIdentity,
    Artifact,
    Decision,
    EnvAdapter,
    GateResult,
    Metric,
    Observation,
    ProtocolSpec,
    Signature,
    SuiteResult,
    SuiteStatus,
    canonical_protocol_hash,
    compose_acceptance_report,
    evaluate_admission,
    skipped_suite,
    suite_tier,
)

__all__ = [
    "ALL_SUITE_IDS",
    "DEFAULT_KERNEL_SUITE_ID",
    "OPTIONAL_SUITE_IDS",
    "REQUIRED_SUITE_IDS",
    "SCHEMA_VERSION",
    "BenchTier",
    "AcceptanceReport",
    "Admission",
    "AdmissionDecision",
    "AgentAdapter",
    "AgentIdentity",
    "Artifact",
    "Decision",
    "EnvAdapter",
    "GateResult",
    "Metric",
    "Observation",
    "ProtocolSpec",
    "Signature",
    "SuiteResult",
    "SuiteStatus",
    "canonical_protocol_hash",
    "compose_acceptance_report",
    "evaluate_admission",
    "skipped_suite",
    "suite_tier",
]
